name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm test -- --coverage --coverageReporters="json-summary" --coverageReporters="lcov" --coverageReporters="text"
    
    - name: Generate coverage badge
      run: |
        if [ -f "coverage/coverage-summary.json" ]; then
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          if [ "$COVERAGE" = "null" ] || [ -z "$COVERAGE" ]; then
            COVERAGE=0
          fi
        else
          COVERAGE=0
        fi
        
        COLOR=$(if [ $(echo "$COVERAGE >= 80" | bc) -eq 1 ]; then echo "green"; elif [ $(echo "$COVERAGE >= 60" | bc) -eq 1 ]; then echo "yellow"; else echo "red"; fi)
        
        MESSAGE="${COVERAGE}%"
        
        echo "{\"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"$MESSAGE\", \"color\": \"$COLOR\"}" > coverage/badge.json
        
        cat coverage/badge.json
    
    - name: Upload coverage to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: coverage
        branch: gh-pages
        clean: true 